### PR TITLE
Upgrade to @zeal/react-scripts 2.0 and latest generator

### PR DESCRIPTION
**Pull request by randycoulman**
Upgrades to the latest version of `@zeal/react-scripts` and the soon-to-be-released version of generator-react-zeal.

Most of the changes here are the result of reformatting the code with prettier's default options.

Other changes:
* Set `APP_PORT` to 4000 in `env.development` so the browser opens to the right URL.
* Add prettier support.
* Set `NODE_PATH` in `.env` to support the new way of resolving imports; related change to the eslint configuration.

### CODE REVIEW

**Comment by lexun** [comment]
Although perhaps not essential for this demo project, I'd still like to make a case for `.env` remaining in the `.gitignore`. Often people will need to make other changes to this file that they wouldn't want to check in, @frank-west-iii perhaps you can drop some notes on your workflow with VMs?

I realize we need the `NODE_PATH` set to resolve with our client folder, but maybe we can do this another way? One option would be putting it in the package.json similar to how we do `BUILD_PATH` [here](https://github.com/CodingZeal/phoenix-react-apollo-demo/blob/670a4699e4b8810d14c0bb63bc2979000f7714a9/package.json#L34). Or maybe bring back the previous solution of having an initial `.env` file generated by a mix task. The task is [still there](https://github.com/CodingZeal/phoenix-react-apollo-demo/blob/master/lib/mix/setup.ex), we'd just need to update it and restore the instructions to `mix todo_app.setup` in the readme like [here](https://github.com/CodingZeal/phoenix-react-apollo-demo/blob/0ac6ff6c42f02fd9abead98402863f966200f31f/README.md).

**Review by lexun — COMMENTED** [review]
With the new `.env` support should we also move the `BUILD_PATH` from the `package.json`? I think it's also safe to say that `lib/mix/setup.ex` is never going to be needed again.

**Comment by randycoulman** [comment]
That's not a bad idea.  I'll add that in here.

**Comment by randycoulman** [comment]
@lexun Comments addressed in 9327628 and e74d986.

**Review by lexun — APPROVED** [review]

**Pull request merged**
